import type { AdminLocale, Localized } from "./admin-locale";

const reasonLabels: Localized<Record<string, string>> = {
  ru: {
    candidate_limit_reached: "Слишком много похожих записей, нужен ручной выбор",
    canonical_url: "Совпадает очищенная ссылка",
    counterpart_location_and_publication_agree: "Компания, локация и дата публикации совпадают",
    counterpart_missing: "Не хватает компании или заказчика для уверенного решения",
    counterparts_incompatible: "Компании или заказчики отличаются",
    descriptions_incompatible: "Описания противоречат друг другу",
    descriptions_not_similar_enough: "Описание недостаточно похоже",
    different_native_ids_in_same_source: "В одном источнике разные внешние ID",
    different_opportunity_types: "Разные типы возможностей",
    different_sources: "Записи найдены в разных источниках",
    different_sources_unverified: "Источники не дают уверенного подтверждения",
    different_tender_lot_numbers: "Разные номера лотов тендера",
    different_tender_lot_url_values: "В ссылках разные значения лота",
    different_tender_notice_numbers: "Разные номера извещений тендера",
    different_tender_notice_url_values: "В ссылках разные значения извещения",
    different_tender_procedure_numbers: "Разные номера процедур тендера",
    different_title_numbers: "В названиях разные номера",
    different_title_seniority: "В названиях разный уровень роли",
    different_title_technologies: "В названиях разные технологии",
    embedding_models_or_tokenizers_incompatible: "AI-сравнение выполнено разными моделями или токенизаторами",
    exact_fingerprint: "Совпадает устойчивый отпечаток записи",
    exact_native_source: "Совпадает внешний ID в источнике",
    exact_normalized_url: "Совпадает очищенная ссылка",
    exact_source_and_external_id: "Совпадает источник и внешний ID",
    explicit_body_technologies_incompatible: "В тексте явно указаны разные технологии",
    explicit_title_technologies_incompatible: "В названии явно указаны разные технологии",
    full_embedding_plan_unavailable: "Нельзя подготовить полный текст для AI-сравнения",
    full_facts_not_serializable: "Не удалось зафиксировать факты для сравнения",
    full_title_and_description_semantically_agree: "AI считает название и описание одним и тем же объявлением",
    full_title_and_description_semantically_distinct: "AI считает название и описание разными объявлениями",
    location_missing: "Не хватает локации для уверенного решения",
    locations_incompatible: "Локации отличаются",
    merge_conflict_requires_review: "Автообъединение остановлено из-за конфликта, нужен ручной разбор",
    opportunity_type_missing: "Не хватает типа возможности",
    opportunity_type_missing_or_incompatible: "Тип возможности отсутствует или отличается",
    publication_date_missing: "Не хватает даты публикации",
    publication_dates_far_apart: "Даты публикации слишком далеко друг от друга",
    publication_dates_not_close: "Даты публикации не совпадают по допустимому окну",
    reliable_description_agrees: "Надёжное описание совпадает",
    reliable_description_missing: "Не хватает надёжного описания",
    same_native_id: "Совпадает внешний ID в источнике",
    same_source_native_id: "Совпадает внешний ID в источнике",
    same_url: "Совпадает ссылка",
    same_company: "Совпадает компания или заказчик",
    same_client: "Совпадает компания или заказчик",
    same_location: "Совпадает локация",
    same_type: "Совпадает тип",
    semantic_chunk_layout_mismatch: "AI-сравнение устарело из-за изменения разбиения текста",
    semantic_embedding_input_mismatch: "AI-сравнение устарело из-за изменения текста",
    semantic_embedding_vector_invalid: "AI-вектор некорректен",
    semantic_evidence_missing: "Нет данных AI-сравнения",
    semantic_evidence_requires_review: "AI-сравнение требует ручного решения",
    semantic_evidence_unavailable: "AI-сравнение временно недоступно",
    semantic_facts_hash_stale: "Факты изменились после AI-сравнения",
    semantic_full_text_coverage_incomplete: "AI-сравнение не покрыло весь текст",
    semantic_full_text_plan_mismatch: "План AI-сравнения устарел",
    semantic_model_metadata_incomplete: "Не хватает сведений о модели AI-сравнения",
    semantic_only_for_ambiguous_candidates: "AI-сравнение применяется только к спорным парам",
    semantic_tokenizer_coverage_unverified: "Не подтверждено, что AI обработал весь текст",
    semantic_l4: "Тексты семантически похожи",
    semantic_review: "AI-сравнение требует решения",
    shared_source_identity_unverified: "Общий источник не подтвердил одинаковую запись",
    tender_lot_identity_unverified: "Лот тендера не подтверждён",
    tender_notice_and_lot_identity_unverified: "Извещение и лот тендера не подтверждены",
    text_candidate_requires_review: "Текст похож, нужен ручной разбор",
    texts_not_similar: "Тексты недостаточно похожи",
    title_and_reliable_description_agree: "Название и надёжное описание совпадают",
    title_exact: "Совпадает название",
    title_missing: "Не хватает названия",
    title_near: "Очень похожее название",
    titles_incompatible: "Названия противоречат друг другу",
    titles_not_similar_enough: "Название недостаточно похоже",
    url_is_only_homepage: "Ссылка ведёт только на главную страницу",
  },
  en: {
    candidate_limit_reached: "Too many similar records; manual choice is needed",
    canonical_url: "Same normalized link",
    counterpart_location_and_publication_agree: "Company, location and publication date match",
    counterpart_missing: "Company or client is missing for a confident decision",
    counterparts_incompatible: "Companies or clients differ",
    descriptions_incompatible: "Descriptions conflict",
    descriptions_not_similar_enough: "Description is not similar enough",
    different_native_ids_in_same_source: "Different external IDs in the same source",
    different_opportunity_types: "Different opportunity types",
    different_sources: "Records come from different sources",
    different_sources_unverified: "Sources do not confidently prove a match",
    different_tender_lot_numbers: "Different tender lot numbers",
    different_tender_lot_url_values: "Different lot values in source links",
    different_tender_notice_numbers: "Different tender notice numbers",
    different_tender_notice_url_values: "Different notice values in source links",
    different_tender_procedure_numbers: "Different tender procedure numbers",
    different_title_numbers: "Different numbers in titles",
    different_title_seniority: "Different seniority in titles",
    different_title_technologies: "Different technologies in titles",
    embedding_models_or_tokenizers_incompatible: "AI comparison used different models or tokenizers",
    exact_fingerprint: "Stable record fingerprint matches",
    exact_native_source: "Same external source ID",
    exact_normalized_url: "Same normalized link",
    exact_source_and_external_id: "Same source and external ID",
    explicit_body_technologies_incompatible: "Body explicitly names different technologies",
    explicit_title_technologies_incompatible: "Title explicitly names different technologies",
    full_embedding_plan_unavailable: "Full text cannot be prepared for AI comparison",
    full_facts_not_serializable: "Comparison facts could not be fixed",
    full_title_and_description_semantically_agree: "AI sees the title and description as the same posting",
    full_title_and_description_semantically_distinct: "AI sees the title and description as different postings",
    location_missing: "Location is missing for a confident decision",
    locations_incompatible: "Locations differ",
    merge_conflict_requires_review: "Auto-merge stopped on a conflict; manual review is needed",
    opportunity_type_missing: "Opportunity type is missing",
    opportunity_type_missing_or_incompatible: "Opportunity type is missing or differs",
    publication_date_missing: "Publication date is missing",
    publication_dates_far_apart: "Publication dates are too far apart",
    publication_dates_not_close: "Publication dates are outside the allowed window",
    reliable_description_agrees: "Reliable description matches",
    reliable_description_missing: "Reliable description is missing",
    same_native_id: "Same external source ID",
    same_source_native_id: "Same external source ID",
    same_url: "Same source link",
    same_company: "Same company or client",
    same_client: "Same company or client",
    same_location: "Same location",
    same_type: "Same type",
    semantic_chunk_layout_mismatch: "AI comparison is stale because text chunks changed",
    semantic_embedding_input_mismatch: "AI comparison is stale because text changed",
    semantic_embedding_vector_invalid: "AI vector is invalid",
    semantic_evidence_missing: "AI comparison data is missing",
    semantic_evidence_requires_review: "AI comparison needs a manual decision",
    semantic_evidence_unavailable: "AI comparison is temporarily unavailable",
    semantic_facts_hash_stale: "Facts changed after AI comparison",
    semantic_full_text_coverage_incomplete: "AI comparison did not cover the full text",
    semantic_full_text_plan_mismatch: "AI comparison plan is stale",
    semantic_model_metadata_incomplete: "AI model metadata is incomplete",
    semantic_only_for_ambiguous_candidates: "AI comparison is only used for ambiguous pairs",
    semantic_tokenizer_coverage_unverified: "Full-text AI coverage is not verified",
    semantic_l4: "Semantically similar text",
    semantic_review: "AI comparison needs a decision",
    shared_source_identity_unverified: "Shared source did not prove the same record",
    tender_lot_identity_unverified: "Tender lot identity is not verified",
    tender_notice_and_lot_identity_unverified: "Tender notice and lot identity are not verified",
    text_candidate_requires_review: "Text candidate needs manual review",
    texts_not_similar: "Texts are not similar enough",
    title_and_reliable_description_agree: "Title and reliable description match",
    title_exact: "Same title",
    title_missing: "Title is missing",
    title_near: "Very similar title",
    titles_incompatible: "Titles conflict",
    titles_not_similar_enough: "Title is not similar enough",
    url_is_only_homepage: "Link points only to the homepage",
  },
};

export function dedupReasonLabel(reason: string | undefined, locale: AdminLocale) {
  if (!reason) return locale === "en" ? "Needs manual review" : "Нужна ручная проверка";
  const key = reason.trim();
  return reasonLabels[locale][key] ?? fallbackReasonLabel(key, locale);
}

export function dedupReasonSummary(reasons: string[] | undefined, locale: AdminLocale) {
  const labels = Array.from(new Set((reasons ?? []).map((reason) => dedupReasonLabel(reason, locale))));
  return labels.length ? labels : [locale === "en" ? "Needs manual review" : "Нужна ручная проверка"];
}

export function confidenceLabel(value: number | null | undefined, locale: AdminLocale) {
  if (typeof value !== "number" || !Number.isFinite(value)) return "—";
  return new Intl.NumberFormat(locale === "en" ? "en-US" : "ru-RU", { maximumFractionDigits: 1, style: "percent" }).format(value);
}

export function numberLabel(value: number | null | undefined, locale: AdminLocale) {
  if (typeof value !== "number" || !Number.isFinite(value)) return "0";
  return new Intl.NumberFormat(locale === "en" ? "en-US" : "ru-RU", { maximumFractionDigits: 0 }).format(value);
}

function fallbackReasonLabel(reason: string, locale: AdminLocale) {
  if (!reason) return locale === "en" ? "Needs manual review" : "Нужна ручная проверка";
  const code = reason.replace(/\s+/g, "_");
  return locale === "en" ? `Needs manual review (${code})` : `Нужна ручная проверка (${code})`;
}
